# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 956530464b0f8912394f9921a9d112502d74026e207e83370cc280f98d8b0fd0ff5283015182ae2ce4c9ed60146df0153f0d9f496aabaa48217e80eb510ae0ac

test:
  secret_key_base: b50966ef284a35eeb05007191f38a0068584f3211d243dd51106d9662811ea098d4a9879094be83bf481407f5cb679f465199902592496e0b02d546d52ca4c2b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
